import { type UserRole } from '@/types/auth';
import { type TourStep, type ChecklistMission } from '@/types/onboarding';

export const ROLE_TOUR_STEPS: Record<UserRole, TourStep[]> = {
  GESTOR: [
    {
      id: 'gestor-welcome',
      title: 'Bem-vindo ao Urboa Gestão',
      description: 'Sua central executiva de manutenção predial e zeladoria urbana. Aqui você monitora conformidade ABNT NBR 5674 e prazos legais.',
      role: 'GESTOR',
      targetSelector: '[data-tour="header-welcome"]',
      position: 'bottom',
      badge: 'Visão Geral',
      actionTip: 'Navegue usando as setas do teclado ou os botões abaixo.',
    },
    {
      id: 'gestor-kpis',
      title: 'Painel de SLAs e Indicadores Críticos',
      description: 'Acompanhe chamados urgentes, dentro do prazo e ordens que exigem escalonamento imediato para evitar paralisações de serviços públicos.',
      role: 'GESTOR',
      targetSelector: '[data-tour="kpi-cards"]',
      position: 'bottom',
      badge: 'SLAs & Metas',
      actionTip: 'Clique em qualquer métrica para filtrar ordens instantaneamente.',
    },
    {
      id: 'gestor-triagem',
      title: 'Fila de Decisões e Triagem',
      description: 'Aprove, ajuste a prioridade e atribua técnicos responsáveis às ordens de serviço recém-chegadas com histórico completo.',
      role: 'GESTOR',
      targetSelector: '[data-tour="triagem-section"]',
      position: 'top',
      badge: 'Despacho Rápido',
      actionTip: 'Você pode aprovar ou reclassificar diretamente pelos atalhos.',
    },
    {
      id: 'gestor-unidades',
      title: 'Inventário de Prédios e Unidades',
      description: 'Consulte o mapa interativo, histórico de manutenções por escola/UBS e estado de conservação de cada patrimônio municipal.',
      role: 'GESTOR',
      targetSelector: '[data-tour="nav-unidades"]',
      position: 'right',
      badge: 'Patrimônio',
      actionTip: 'Acesse o menu lateral para gerenciar os edifícios cadastrados.',
    },
    {
      id: 'gestor-copilot',
      title: 'Copilot Inteligente de Zeladoria',
      description: 'Consulte análises preventivas, descubra reincidências de falhas e peça resumos executivos diretamente à inteligência artificial.',
      role: 'GESTOR',
      targetSelector: '[data-tour="copilot-button"]',
      position: 'right',
      badge: 'IA Integrada',
      actionTip: 'Clique no ícone de fagulhas ou use Ctrl+K para abrir o Copilot.',
    },
  ],

  SOLICITANTE: [
    {
      id: 'solicitante-welcome',
      title: 'Portal de Zeladoria da sua Unidade',
      description: 'Facilitamos a comunicação entre diretores de escolas, gerentes de UBSs e a equipe central de manutenção municipal.',
      role: 'SOLICITANTE',
      targetSelector: '[data-tour="header-welcome"]',
      position: 'bottom',
      badge: 'Seu Espaço',
      actionTip: 'Todas as ocorrências registradas aqui são atendidas pela Prefeitura.',
    },
    {
      id: 'solicitante-novo-chamado',
      title: 'Abertura de Chamado em 45 Segundos',
      description: 'Descreva o problema predial (elétrica, hidráulica, infiltração), anexe fotos de comprovação e informe a urgência com facilidade.',
      role: 'SOLICITANTE',
      targetSelector: '[data-tour="solicitante-novo-chamado"]',
      position: 'bottom',
      badge: 'Ação Principal',
      actionTip: 'Fotos nítidas ajudam o técnico a levar as peças corretas no primeiro atendimento.',
    },
    {
      id: 'solicitante-meus-chamados',
      title: 'Acompanhamento do Ciclo de Vida da OS',
      description: 'Veja se sua solicitação foi recebida, triada, se há técnico em trânsito e o relatório fotográfico de conclusão do serviço.',
      role: 'SOLICITANTE',
      targetSelector: '[data-tour="solicitante-chamados-list"]',
      position: 'top',
      badge: 'Transparência',
      actionTip: 'Clique em qualquer chamado para ver a linha do tempo detalhada.',
    },
    {
      id: 'solicitante-notificacoes',
      title: 'Alertas e Atualizações em Tempo Real',
      description: 'Você recebe notificações sempre que um técnico for atribuído ou quando o reparo na sua unidade for concluído com sucesso.',
      role: 'SOLICITANTE',
      targetSelector: '[data-tour="notifications-bell"]',
      position: 'bottom',
      badge: 'Alertas',
      actionTip: 'O sino exibe avisos sem necessidade de recarregar a página.',
    },
  ],

  TECNICO: [
    {
      id: 'tecnico-welcome',
      title: 'Painel Operacional do Técnico',
      description: 'Sua escala diária, ordens de serviço sob sua responsabilidade e relatórios de execução em campo.',
      role: 'TECNICO',
      targetSelector: '[data-tour="header-welcome"]',
      position: 'bottom',
      badge: 'Operação',
      actionTip: 'Otimizado para consulta rápida no celular ou tablet.',
    },
    {
      id: 'tecnico-chamados',
      title: 'Ordens Atribuídas a Você',
      description: 'Visualize prioridades, endereço do prédio, contato do solicitante e detalhes da ocorrência.',
      role: 'TECNICO',
      targetSelector: '[data-tour="triagem-section"]',
      position: 'top',
      badge: 'Execução',
      actionTip: 'Altere o status para "Em Execução" ao chegar ao local da ocorrência.',
    },
    {
      id: 'tecnico-agenda',
      title: 'Agenda de Vistorias e Rotas',
      description: 'Confira os agendamentos de manutenção preventiva e vistorias programadas para o seu turno.',
      role: 'TECNICO',
      targetSelector: '[data-tour="nav-agenda"]',
      position: 'right',
      badge: 'Itinerário',
      actionTip: 'Mantenha sua lista de vistorias sempre atualizada.',
    },
  ],

  ADMIN: [
    {
      id: 'admin-welcome',
      title: 'Administração & Governança Urboa',
      description: 'Gestão completa de usuários, papéis RBAC, prédios públicos, parametrização de SLAs e trilhas de auditoria.',
      role: 'ADMIN',
      targetSelector: '[data-tour="header-welcome"]',
      position: 'bottom',
      badge: 'Controle Total',
    },
    {
      id: 'admin-kpis',
      title: 'Métricas Globais de Zeladoria',
      description: 'Acompanhe MTTR (tempo médio de reparo), custos operacionais e metas de manutenção preventiva da gestão municipal.',
      role: 'ADMIN',
      targetSelector: '[data-tour="kpi-cards"]',
      position: 'bottom',
      badge: 'Auditoria & SLAs',
    },
    {
      id: 'admin-config',
      title: 'Configurações e Parâmetros Institucionais',
      description: 'Defina limites de SLA da prefeitura, contatos oficiais e consulte os logs imutáveis para o Tribunal de Contas.',
      role: 'ADMIN',
      targetSelector: '[data-tour="nav-configuracoes"]',
      position: 'right',
      badge: 'Governança',
    },
    {
      id: 'admin-copilot',
      title: 'Copilot & Inteligência de Dados',
      description: 'Utilize modelos avançados para auditoria de produtividade técnica e previsão de manutenções preventivas.',
      role: 'ADMIN',
      targetSelector: '[data-tour="copilot-button"]',
      position: 'right',
      badge: 'Inteligência Artificial',
    },
  ],
};

export const ROLE_CHECKLIST_MISSIONS: Record<UserRole, ChecklistMission[]> = {
  GESTOR: [
    {
      id: 'mission-tour',
      title: 'Completar o Tour Guiado do Gestor',
      description: 'Conheça todos os módulos essenciais da plataforma.',
      isCompleted: false,
    },
    {
      id: 'mission-kpi',
      title: 'Revisar os Indicadores de SLA',
      description: 'Verifique se há ordens que exigem escalonamento urgente.',
      isCompleted: false,
      actionRoute: '/',
      actionLabel: 'Ver Indicadores',
    },
    {
      id: 'mission-triagem',
      title: 'Inspecionar a Fila de Triagem',
      description: 'Analise os chamados recém-enviados pelas unidades.',
      isCompleted: false,
      actionRoute: '/chamados',
      actionLabel: 'Acessar Chamados',
    },
    {
      id: 'mission-unidades',
      title: 'Explorar o Inventário de Prédios',
      description: 'Consulte as escolas e postos de saúde cadastrados.',
      isCompleted: false,
      actionRoute: '/unidades',
      actionLabel: 'Ver Prédios',
    },
    {
      id: 'mission-copilot',
      title: 'Experimentar o Copilot IA',
      description: 'Faça uma consulta sobre reincidência de problemas ou SLAs.',
      isCompleted: false,
      actionLabel: 'Abrir Copilot',
    },
  ],

  SOLICITANTE: [
    {
      id: 'mission-tour',
      title: 'Completar o Tour do Solicitante',
      description: 'Aprenda como funciona o fluxo de manutenção da sua unidade.',
      isCompleted: false,
    },
    {
      id: 'mission-primeiro-chamado',
      title: 'Simular ou Abrir um Chamado',
      description: 'Registre uma necessidade real ou de teste para sua escola/UBS.',
      isCompleted: false,
      actionRoute: '/abrir-chamado',
      actionLabel: 'Novo Chamado',
    },
    {
      id: 'mission-acompanhamento',
      title: 'Verificar Linha do Tempo das OSs',
      description: 'Veja como acompanhar o deslocamento e resolução técnica.',
      isCompleted: false,
      actionRoute: '/',
      actionLabel: 'Minhas Ordens',
    },
  ],

  TECNICO: [
    {
      id: 'mission-tour',
      title: 'Completar o Tour do Técnico',
      description: 'Entenda como gerenciar seus atendimentos e registrar fotos.',
      isCompleted: false,
    },
    {
      id: 'mission-os',
      title: 'Consultar Ordens em Aberto',
      description: 'Veja os detalhes do chamado atribuído à sua equipe.',
      isCompleted: false,
      actionRoute: '/chamados',
      actionLabel: 'Ver Ordens',
    },
    {
      id: 'mission-agenda',
      title: 'Verificar Agenda de Vistorias',
      description: 'Confira as datas e horários dos serviços de campo.',
      isCompleted: false,
      actionRoute: '/agenda',
      actionLabel: 'Ver Agenda',
    },
  ],

  ADMIN: [
    {
      id: 'mission-tour',
      title: 'Completar o Tour do Administrador',
      description: 'Entenda os recursos de governança e auditoria da gestão.',
      isCompleted: false,
    },
    {
      id: 'mission-auditoria',
      title: 'Verificar Parâmetros de SLA e Auditoria',
      description: 'Confira os prazos regulamentares da prefeitura.',
      isCompleted: false,
      actionRoute: '/configuracoes',
      actionLabel: 'Configurações',
    },
    {
      id: 'mission-dev',
      title: 'Conhecer o Painel Dev & Diagnósticos',
      description: 'Use Ctrl+Shift+D para verificar o status do banco e API.',
      isCompleted: false,
      actionLabel: 'Ver Diagnósticos',
    },
  ],
};
